-- audit_log table for tracking all changes
create table if not exists workflows_manager.audit_log
(
    id         bigint generated by default as identity
        constraint pk_audit_log primary key,
    entity     varchar(100)                           not null,
    entity_id  varchar(255)                           not null,
    username   workflows_manager.username             not null,
    action     varchar(50)                            not null,
    created_at timestamp with time zone default now() not null
);

create index if not exists idx_audit_log_entity_entity_id on workflows_manager.audit_log (entity, entity_id);
create index if not exists idx_audit_log_username on workflows_manager.audit_log (username);
create index if not exists idx_audit_log_created_at on workflows_manager.audit_log (created_at);

